on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v2.x

    - name: Install dependencies
      run: deno install --frozen

    - name: Create Google Service Account file for testing Google Play auth 
      uses: levibostian/action-random-file@main
      id: create-google-play-service-account-file
      with:
        base64-file-content: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_FILE_B64 }}
        file-name: "service_account.json"      

    - name: Compile the binary 
      run: deno task compile-for-this-os

    - name: Run auth command to test the tool works as expected
      run: |
        ./upload-android-app-to-google-play auth-check \
          --package-name earth.levi.bluetoothbattery \
          --service-account ${{ steps.create-google-play-service-account-file.outputs.path }}
